# Navigate to server directory

# Create main directories
mkdir -p {models,middleware,routes,controllers,config,utils,validations,services}
mkdir -p migrations seeders uploads/{images,avatars} public

# Create nested structure for routes
mkdir -p routes/{api,v1}
mkdir -p routes/api/{auth,users,posts,categories,comments}

# Create nested structure for controllers
mkdir -p controllers/{auth,users,posts,categories,comments}

# Create nested structure for middleware
mkdir -p middleware/{auth,validation,upload,error}

# Create nested structure for utils
mkdir -p utils/{helpers,database,validators}

# Config files
touch config/database.js
touch config/sequelize.js
touch config/upload.js
touch config/jwt.js

# Server files
touch server.js
touch .sequelizerc

# Model files
touch models/index.js
touch models/User.js
touch models/Post.js
touch models/Category.js
touch models/Comment.js
touch models/Tag.js
touch models/PostTag.js

# Middleware files
touch middleware/index.js
touch middleware/auth/authenticate.js
touch middleware/auth/authorize.js
touch middleware/validation/userValidation.js
touch middleware/validation/postValidation.js
touch middleware/upload/imageUpload.js
touch middleware/error/errorHandler.js
touch middleware/error/notFound.js

# Route files
touch routes/index.js
touch routes/api/index.js
touch routes/api/auth.js
touch routes/api/users.js
touch routes/api/posts.js
touch routes/api/categories.js
touch routes/api/comments.js

# Controller files
touch controllers/index.js
touch controllers/authController.js
touch controllers/userController.js
touch controllers/postController.js
touch controllers/categoryController.js
touch controllers/commentController.js

# Service files (business logic)
touch services/userService.js
touch services/postService.js
touch services/authService.js

# Utility files
touch utils/index.js
touch utils/helpers/response.js
touch utils/helpers/logger.js
touch utils/database/dbHelper.js
touch utils/validators/userValidator.js

# Validation files
touch validations/userValidation.js
touch validations/postValidation.js
touch validations/authValidation.js

# Migration files (will be generated by Sequelize later)
touch migrations/.gitkeep

# Seeder files (will be generated by Sequelize later)
touch seeders/.gitkeep

# Public files
touch public/index.html
touch public/robots.txt

# Documentation
touch README.md
touch API_DOCS.md